version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: nest-app
    container_name: vcp-database
    command: ['node', 'dist/main']
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vcpdb
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
